POST http://localhost:13337/api/environments
Content-Type: application/json

{
    "name": "mike"
}

###

GET http://localhost:13337/api/environments/mike
Content-Type: application/json

{}

###

PUT http://localhost:13337/api/environments/mike
Content-Type: application/json

{
    "name": "mike"
}

###

DELETE http://localhost:13337/api/environments/mike
Content-Type: application/json

{}

###