POST http://localhost:13337/api/environments
Content-Type: application/json

{
    "name": "mike",
    "aws_access_key_id": "{{$dotenv AWS_ACCESS_KEY_ID}}",
    "aws_secret_access_key": "{{$dotenv AWS_SECRET_ACCESS_KEY}}",
    "aws_region": "{{$dotenv AWS_REGION}}"
}

###

GET http://localhost:13337/api/environments/mike
Content-Type: application/json

{
    "aws_access_key_id": "{{$dotenv AWS_ACCESS_KEY_ID}}",
    "aws_secret_access_key": "{{$dotenv AWS_SECRET_ACCESS_KEY}}",
    "aws_region": "{{$dotenv AWS_REGION}}"
}

###

PUT http://localhost:13337/api/environments/mike
Content-Type: application/json

{
    "name": "mike",
    "aws_access_key_id": "{{$dotenv AWS_ACCESS_KEY_ID}}",
    "aws_secret_access_key": "{{$dotenv AWS_SECRET_ACCESS_KEY}}",
    "aws_region": "{{$dotenv AWS_REGION}}"
}

###

DELETE http://localhost:13337/api/environments/mike
Content-Type: application/json

{
    "aws_access_key_id": "{{$dotenv AWS_ACCESS_KEY_ID}}",
    "aws_secret_access_key": "{{$dotenv AWS_SECRET_ACCESS_KEY}}",
    "aws_region": "{{$dotenv AWS_REGION}}"
}

###