POST http://localhost:13337/api/environments
Content-Type: application/json

{
    "name": "mike",
    "dns_zone_id": "Z39EZA6EWSOY2X",
    "domain": "520152236921.ritdu.tech"
}

###

GET http://localhost:13337/api/environments/mike
Content-Type: application/json

{}

###

PUT http://localhost:13337/api/environments/mike
Content-Type: application/json

{
    "name": "mike",
    "dns_zone_id": "Z39EZA6EWSOY2X",
    "domain": "520152236921.ritdu.tech"
}

###

DELETE http://localhost:13337/api/environments/mike
Content-Type: application/json

{}

###